name: hado lint test

on:
  workflow_dispatch:

jobs:

  security:

    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run hado-lint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
        continue-on-error: true
          

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sample.sarif
