name: Ansible lint test

on:
  workflow_dispatch:

jobs:

  security:

    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run ansible-lint
        id: run_ansible_lint
        uses: ansible-community/ansible-lint-action@main
        with:
          path: "examples/playbooks/example.yml"
        continue-on-error: true
          
      - name: test output
        run: echo "${{join(steps.run_ansible_lint.outputs.*, '\n')}}"

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sample.sarif
